### PR TITLE
Replace node_tuple with layer_tuple to fix graph networks.

### LINKED ISSUE #146: Split and Concat layers
Hi @nyanp,

great work with tiny-cnn! It should be super helpful for CNN deployment!

I was just testing its abilities and tried a GoogLeNet architecture, when I noticed that it does not support concat/split layers (error: tiny-cnn does not support this layer type:Split). This should be quite easy to implement and would extend its 'range' quite a bit with networks requiring this capability.

### LINKED ISSUE #578: Misused comma operator in serialization test
In https://github.com/tiny-dnn/tiny-dnn/blob/master/test/test_serialization.h#L408
```cpp
s1 << (f2, f3) << c4;
```
intends to connect both f2 and f3 to s1 and c4, but it actually connects only f3 (this is how comma operator works).

Solution proposed by @edgarriba is to use a dynamic array (probably initialization list would work nice here: `s1 << {f2, f3} << c4;`) instead.

### PR DESCRIPTION
**Pull request by karandesai-96**
This PR replaces `node_tuple` with a `layer_tuple` and puts a constraint on its formation in such a way that the passed operands to `,` comma operator have layer class as its ancestor.

The comma operator for node_tuple didn't work if both operands were a different type. Hence one couldn't do `(l1, l2) << l3` and form a graph network if l1 and l2 were not the instances of same type of layer.

Fixes #578. 
Resolves #146, #257, #615.

### CODE REVIEW

**Comment by karandesai-96** [comment]
Example formation of a graph network:
graph

As can be seen, a `fully_connected` layer and a `tanh` layer could be concatenated successfully now. This graph is a formation from code sample by https://github.com/tiny-dnn/tiny-dnn/issues/578#issuecomment-282402095

File: tiny_dnn/node.h [hunk 1]
```diff
@@ -197,40 +209,37 @@ inline std::shared_ptr<U> &operator<<(std::shared_ptr<T> &lhs,
...
-  for (serial_size_t i = 0; i < static_cast<serial_size_t>(rhs.nodes_.size());
-       i++) {
-    connect(&lhs, rhs.nodes_[i], i, 0);
+template <typename T>
+inline layer_tuple<layerptr_t> &operator<<(T &lhs,
+                                           const layer_tuple<layerptr_t> &rhs) {
+  for (size_t i = 0; i < static_cast<size_t>(rhs.layers_.size()); i++) {
+    connect(&lhs, rhs.layers_[i], i, 0);
   }
   return rhs;
```
Comment (Randl) [inline tiny_dnn/node.h]: Seems like returning `rhs` as non-const reference is a problem since you pass it a const reference. Either add `const` qualifier to return type or drop it from parameter type (first is better, if possible)

**Comment by Randl** [comment]
Can you add tests for the new functionality?

**Comment by karandesai-96** [comment]
@Randl sure. On a separate note, the coverage drop is due to something else, I'm confused how.

**Comment by karandesai-96** [comment]
@edgarriba Every time I make some changes, some of all jobs fail. The failure states that `layer.prev_nodes()` are ordered in a different way than specified in a `layer_tuple`.

`l1 << (l2, l3)` should have `l1.prev_nodes()` as `{&l2, &l3}` but on some jobs it is `{&l3, &l2}`, can't understand why.

File: tiny_dnn/node.h (hunk 1 above)
Comment (karandesai-96) [inline tiny_dnn/node.h]: Right, that rectified the error.

File: test/test_node.h [hunk 2]
```diff
@@ -92,4 +92,73 @@ TEST(layer_tuple, comma_operator_layer_tuple2) {
...
+  EXPECT_EQ(fc2->next_nodes()[0], sgm.get());
+}
+
+TEST(layer_tuple, chain_operator_tuple_layer1) {
+  fully_connected_layer fc1(2, 2);
+  fully_connected_layer fc2(2, 2);
+  concat_layer conc({shape3d(2, 1, 1), shape3d(2, 1, 1)});
+  sigmoid_layer sgm(4);
+
+  (fc1, fc2) << conc << sgm;
```
Comment (edgarriba) [inline test/test_node.h]: Just to see the logic working, we could also check previous nodes from conc

File: test/test_node.h [hunk 3]
```diff
@@ -92,4 +92,73 @@ TEST(layer_tuple, comma_operator_layer_tuple2) {
...
+}
+
+TEST(layer_tuple, chain_operator_layer_tuple1) {
+  convolutional_layer conv(5, 5, 3, 1, 6);
+  slice_layer slice(shape3d(3, 3, 6), slice_type::slice_channels, 2);
+  tanh_layer tanh(3, 3, 3);
+  relu_layer relu(3, 3, 3);
+
+  conv << slice << (tanh, relu);
+  EXPECT_EQ(slice.prev_nodes()[0], &conv);
```
Comment (edgarriba) [inline test/test_node.h]: And here check next

File: test/test_node.h [hunk 4]
```diff
@@ -92,4 +92,73 @@ TEST(layer_tuple, comma_operator_layer_tuple2) {
...
+}
+
+TEST(layer_tuple, chain_operator_layer_tuple2) {
+  auto conv  = std::make_shared<convolutional_layer>(5, 5, 3, 1, 6);
+  auto slice = std::make_shared<slice_layer>(shape3d(3, 3, 6),
+                                             slice_type::slice_channels, 2);
+  auto tanh = std::make_shared<tanh_layer>(3, 3, 3);
+  auto relu = std::make_shared<relu_layer>(3, 3, 3);
+
+  conv << slice << (tanh, relu);
```
Comment (edgarriba) [inline test/test_node.h]: And next

File: test/test_node.h (hunk 2 above)
Comment (karandesai-96) [inline test/test_node.h]: There was a check, but the order in `prev_nodes ()` vector gets jumbled sometimes. I am unable to compare pointers directly based on index.

This problem happens only on clang.

Comment (edgarriba) [inline test/test_node.h]: Did you check locally with clang?

Comment (karandesai-96) [inline test/test_node.h]: Yes, it fails. Address of `fc1` is `prev_nodes()[1]` and address of `fc2` is `prev_nodes()[0]` when I use clang, hence the test fails.

Comment (karandesai-96) [inline test/test_node.h]: @edgarriba shall I get it done by #ifdef macros ?

Comment (edgarriba) [inline test/test_node.h]: No macros, we have to make sure that this behavior doesn't lead to future bugs

File: tiny_dnn/node.h [hunk 5]
```diff
@@ -158,79 +158,105 @@ inline std::vector<node *> node::next_nodes() const {
...
 }
 
-template <typename T, typename U>
-inline U &operator<<(const node_tuple<T> &lhs, U &rhs) {
-  for (serial_size_t i = 0; i < static_cast<serial_size_t>(lhs.nodes_.size());
-       i++) {
-    connect(&*lhs.nodes_[i], &*rhs, 0, i);
+template <typename T>
+inline T &operator<<(const layer_tuple<std::shared_ptr<layer>> &lhs, T &rhs) {
+  for (size_t i = 0; i < static_cast<size_t>(lhs.layers_.size()); i++) {
```
Comment (beru) [inline tiny_dnn/node.h]: How about using Range-based for loop?

Comment (Randl) [inline tiny_dnn/node.h]: Anyway, why do we need cast here?

Comment (karandesai-96) [inline tiny_dnn/node.h]: @beru we need to provide index of node during connection to maintain order during operations such as channel concatenation during merging. So range-based for loops might not be a good choice.

Comment (beru) [inline tiny_dnn/node.h]: @karandesai-96 You're right. I didn't check the argument.

**Comment by beru** [comment]
I wonder if
```cpp
typedef layer *layerptr_t;
```
is really required....

**Comment by karandesai-96** [comment]
@beru @edgarriba how about now?

**Comment by beru** [comment]
One thing I noticed is `const_cast` is used in several places.
```cpp
const_cast<layer *>(this)->ith_out_node
const_cast<layer *>(this)->ith_in_node
```
Maybe having `const` versions of `layer::ith_in_node` and `layer::ith_in_node` might be better?

**Comment by beru** [comment]
@edgarriba Please check the change.

**Comment by edgarriba** [comment]
LGTM
